In [2]:
import torch
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [8]:
x.shape #访问形状

torch.Size([12])

In [16]:
x.numel()#访问张量中的元素个数

12

In [12]:
X = x.reshape(3, 4)#改变张量的维度
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [15]:
X.shape#一个二维张量，3行四列

torch.Size([3, 4])

In [19]:
Z = torch.zeros((2, 3, 4))#创建两个3行4列的矩阵，第一个2表示有两个这样的矩阵，这是一个3d的数据，2表示深度
Z

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [20]:
O = torch.ones((2, 3, 4))
O

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])